trigger:
  branches:
    include:
      - main

stages:
- stage: SharedServices
  displayName: 'Deploy Shared Services'
  jobs:
  - job: DeploySharedServices
    displayName: 'Deploy Shared Services Resources'
    pool:
      name: 'IaC-agent-pool'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Shared Services Bicep'
      inputs:
        azureSubscription: 'SharedServices-ARM'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "Azure sub1"
          az group create --name rg-shared-services --location northeurope
          $output = az deployment group create `
            --resource-group rg-shared-services `
            --template-file infra/stacks/shared-services/main.bicep `
            --parameters "@infra/stacks/shared-services/main.json" `
            --output json
          Write-Host "Shared Services Deployment Output: $output"

- stage: CompanyA
  displayName: 'Deploy Company A'
  dependsOn: SharedServices
  jobs:
  - job: DeployCompanyA
    displayName: 'Deploy Company A Resources'
    pool:
      name: 'IaC-agent-pool'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Company A Bicep'
      inputs:
        azureSubscription: 'CompanyA-ARM'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "Azure Sub-A"
          az group create --name rg-company-a --location northeurope
          $output = az deployment group create `
            --resource-group rg-company-a `
            --template-file infra/stacks/company-a/main.bicep `
            --parameters "@infra/stacks/company-a/company-a.parameters.json" `
            --output json
          Write-Host "Company A Deployment Output: $output"

- stage: CompanyB
  displayName: 'Deploy Company B'
  dependsOn: SharedServices
  jobs:
  - job: DeployCompanyB
    displayName: 'Deploy Company B Resources'
    pool:
      name: 'IaC-agent-pool'
    steps:
    - task: AzureKeyVault@2
      displayName: 'Fetch CompanyBAdminPassword from Key Vault'
      inputs:
        azureSubscription: 'CompanyB-ARM'
        KeyVaultName: 'sharedServicesKV25momo'
        SecretsFilter: 'CompanyBAdminPassword'
        RunAsPreJob: true

    - task: AzureCLI@2
      displayName: 'Deploy Company B Bicep'
      inputs:
        azureSubscription: 'CompanyB-ARM'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "Azure Sub-B"
          az group create --name rg-company-b --location northeurope
          $output = az deployment group create `
            --resource-group rg-company-b `
            --template-file infra/stacks/company-b/main.bicep `
            --parameters "@infra/stacks/company-b/company-b.parameters.json" `
                         adminPassword="$(CompanyBAdminPassword)" `
            --output json
          Write-Host "Company B Deployment Output: $output"

# ========================
# Best Practices/Reminders:
# - Ensure parameter files do not store secrets directly; use Key Vault if needed.
# - Ensure agent pool 'IaC-agent-pool' has permissions for Azure CLI.
# - Validate Bicep template paths are correct.
# - Capture deployment output for troubleshooting.
# - Consider using variables for resource group/location if re-used.
