trigger:
  branches:
    include:
      - main

variables:
  hubSubscription: "Azure sub1"
  spoke1Subscription: "Azure Sub-A"
  spoke2Subscription: "Azure Sub-B"
  location: "northeurope"
  keyVaultName: "sharedServicesKV-Mohsen"
  domainName: "contoso.local"
  domainSecurityGroup: "AADDSAdmins"

stages:
- stage: SharedServices
  displayName: 'Deploy Shared Services (Hub)'
  jobs:
    - job: DeploySharedServices
      displayName: 'Deploy Hub Resources'
      pool:
        name: 'IaC-agent-pool'
      steps:
        - task: AzureCLI@2
          displayName: 'Deploy Shared Services Bicep'
          inputs:
            azureSubscription: 'WIF-HubSpokes-Root'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az account set --subscription "Azure sub1"
              az group create --name rg-shared-services --location northeurope
              az deployment group create --resource-group rg-shared-services `
                --template-file infra/stacks/shared-services/main.bicep --parameters "@infra/stacks/shared-services/main.json" `
                --only-show-errors `
                --output none

- stage: ManualApproval
  displayName: 'Manual Approval Before Spokes'
  dependsOn: SharedServices
  jobs:
    - job: WaitForApproval
      displayName: 'Wait for Manual Approval'
      pool: server
      steps:
        - task: ManualValidation@0
          inputs:
            notifyUsers: 'boxclean@gmail.com'
            instructions: 'Please review the Shared Services deployment before proceeding to Spoke deployments.'
            timeout: '0'

- stage: CompanyA
  displayName: 'Deploy Company A (Spoke 1)'
  dependsOn: ManualApproval
  jobs:
    - job: DeployCompanyA
      displayName: 'Deploy Company A Resources'
      pool:
        name: 'IaC-agent-pool'
      steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: '$(wifServiceConnection)'
            KeyVaultName: 'sharedServicesKV-Mohsen'
            SecretsFilter: 'CompanyAAdminUsername,CompanyAAdminPassword'
            RunAsPreJob: true
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Deploy Company A Bicep (ARM Task)'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'WIF-HubSpokes-Root'
            subscriptionId: 'bc590447-877b-4cb2-9253-6d4aab175a22'
            resourceGroupName: 'rg-company-a'
            location: 'northeurope'
            templateLocation: 'Linked artifact'
            csmFile: 'infra/stacks/company-a/main.bicep'
            csmParametersFile: 'infra/stacks/company-a/company-a.parameters.json'
            overrideParameters: >
              -adminUsername "$(CompanyAAdminUsername)"
              -adminPassword "$(CompanyAAdminPassword)"
            deploymentMode: 'Incremental'

- stage: CompanyB
  displayName: 'Deploy Company B (Spoke 2)'
  dependsOn: ManualApproval
  jobs:
    - job: DeployCompanyB
      displayName: 'Deploy Company B Resources'
      pool:
        name: 'IaC-agent-pool'
      steps:
        - task: AzureCLI@2
          displayName: 'Deploy Company B Bicep'
          inputs:
            azureSubscription: '$(wifServiceConnection)'
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az account set --subscription "Azure Sub-B"
              az group create --name rg-company-b --location northeurope
              az deployment group create --resource-group rg-company-b `
                --template-file infra/stacks/company-b/main.bicep --parameters "@infra/stacks/company-b/company-b.parameters.json" `
                --only-show-errors `
                --output none
