trigger:
  branches:
    include:
      - main

variables:
  hubSubscription: "Azure sub1"
  spoke1Subscription: "Azure Sub-A"
  spoke2Subscription: "Azure Sub-B"
  location: "northeurope"
  keyVaultName: "sharedServicesKV-Mohsen"
  wifServiceConnection: "WIF-HubSpokes-Root"
  domainName: "contoso.local"
  domainSecurityGroup: "AADDSAdmins"

stages:

# ==============================
# Stage 1: Deploy Hub / Shared Services
# ==============================
- stage: SharedServices
  displayName: 'Deploy Shared Services (Hub)'
  jobs:
  - job: DeploySharedServices
    displayName: 'Deploy Hub Resources'
    pool:
      name: 'IaC-agent-pool'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Shared Services Bicep'
      inputs:
        azureSubscription: '${{ variables.wifServiceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "$hubSubscription"
          az group create --name rg-shared-services --location "$location"
          output=$(az deployment group create \
            --resource-group rg-shared-services \
            --template-file infra/stacks/shared-services/main.bicep \
            --parameters "@infra/stacks/shared-services/main.json" \
            --output json)
          if [ -z "$output" ]; then
            echo "Deployment output is empty. See deployment errors above."
            exit 1
          fi
          addsSubnetAId=$(echo "$output" | jq -r '.properties.outputs.addsSubnetAId.value')
          addsSubnetBId=$(echo "$output" | jq -r '.properties.outputs.addsSubnetBId.value')
          keyVaultId=$(echo "$output" | jq -r '.properties.outputs.keyVaultId.value')
          echo "##vso[task.setvariable variable=addsSubnetAId;isOutput=true]$addsSubnetAId"
          echo "##vso[task.setvariable variable=addsSubnetBId;isOutput=true]$addsSubnetBId"
          echo "##vso[task.setvariable variable=keyVaultId;isOutput=true]$keyVaultId"

# ==============================
# Stage 1.5: Manual Approval
# ==============================
- stage: ManualApproval
  displayName: 'Manual Approval Before Spokes'
  dependsOn: SharedServices
  jobs:
  - job: WaitForApproval
    displayName: 'Wait for Manual Approval'
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'boxclean@gmail.com'
        instructions: 'Please review the Shared Services deployment before proceeding to Spoke deployments.'
        timeout: '0'

# ==============================
# Stage 2: Deploy Azure AD DS in Hub
# ==============================
- stage: DeployAzureADDS
  displayName: 'Deploy Azure AD DS in Hub'
  dependsOn: ManualApproval
  jobs:
  - job: DeployAzureADDS
    displayName: 'Deploy Azure AD DS'
    pool:
      name: 'IaC-agent-pool'
    variables:
      keyVaultId: $[stageDependencies.SharedServices.DeploySharedServices.outputs['keyVaultId']]
      addsSubnetAId: $[stageDependencies.SharedServices.DeploySharedServices.outputs['addsSubnetAId']]
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Azure AD DS Bicep'
      inputs:
        azureSubscription: '${{ variables.wifServiceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "$hubSubscription"
          az group create --name rg-shared-services --location "$location"
          output=$(az deployment group create \
            --resource-group rg-shared-services \
            --template-file infra/stacks/shared-services/azure-adds.bicep \
            --parameters location="$location" \
                         subnetId="$addsSubnetAId" \
                         domainName="$domainName" \
                         domainSecurityGroupName="$domainSecurityGroup" \
            --output json)
          if [ -z "$output" ]; then
            echo "Deployment output is empty. See deployment errors above."
            exit 1
          fi
          addsDnsIps=$(echo "$output" | jq -r '.properties.outputs.addsDnsIps.value | join(",")')
          echo "##vso[task.setvariable variable=addsDnsIps;isOutput=true]$addsDnsIps"

# ==============================
# Stage 3: Deploy Spoke 1 / Company A
# ==============================
- stage: CompanyA
  displayName: 'Deploy Company A (Spoke 1)'
  dependsOn: DeployAzureADDS
  jobs:
  - job: DeployCompanyA
    displayName: 'Deploy Company A Resources'
    pool:
      name: 'IaC-agent-pool'
    variables:
      addsDnsIps: $[stageDependencies.DeployAzureADDS.DeployAzureADDS.outputs['addsDnsIps']]
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Company A Bicep'
      inputs:
        azureSubscription: '${{ variables.wifServiceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "$spoke1Subscription"
          az group create --name rg-company-a --location "$location"
          az deployment group create \
            --resource-group rg-company-a \
            --template-file infra/stacks/company-a/main.bicep \
            --parameters "@infra/stacks/company-a/company-a.parameters.json" \
                         dnsServerIp="$addsDnsIps" \
            --output json

# ==============================
# Stage 4: Deploy Spoke 2 / Company B
# ==============================
- stage: CompanyB
  displayName: 'Deploy Company B (Spoke 2)'
  dependsOn: DeployAzureADDS
  jobs:
  - job: DeployCompanyB
    displayName: 'Deploy Company B Resources'
    pool:
      name: 'IaC-agent-pool'
    variables:
      addsDnsIps: $[stageDependencies.DeployAzureADDS.DeployAzureADDS.outputs['addsDnsIps']]
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Company B Bicep'
      inputs:
        azureSubscription: '${{ variables.wifServiceConnection }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az account set --subscription "$spoke2Subscription"
          az group create --name rg-company-b --location "$location"
          az deployment group create \
            --resource-group rg-company-b \
            --template-file infra/stacks/company-b/main.bicep \
            --parameters "@infra/stacks/company-b/company-b.parameters.json" \
                         dnsServerIp="$addsDnsIps" \
            --output json
